runtime: nodejs20
env: standard
instance_class: F1
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic
handlers:
  - url: /.*
    secure: always
    script: auto